package org.firstinspires.ftc.teamcode;

//This is a template to start a new TeleOp OpMode
//Please do not edit this file directly.  Instead, create a new Java Class under TeamCode and copy this into it

//Import Statements Go Here
import com.qualcomm.robotcore.eventloop.opmode.TeleOp;
import com.qualcomm.robotcore.eventloop.opmode.OpMode;
import com.qualcomm.robotcore.hardware.DcMotor;


@TeleOp(name="AAA_TeleOp_Template", group="TeleOp") //Change "AAA_TeleOp_Template" to the name of your OpMode
public class AAA_TeleOp_Template extends OpMode {

  //Declare Variables Here
private DcMotor leftDrive;
private DcMotor rightDrive;





    @Override
    public void init() {

        //Code here will be run once when the driver hits INIT
        //This would be a good place to initialize your hardware

        leftDrive = hardwareMap.get(DcMotor.class, "left_drive");
        rightDrive = hardwareMap.get(DcMotor.class, "right_drive");

        leftDrive.setDirection(DcMotor.Direction.REVERSE);
        rightDrive.setDirection(DcMotor.Direction.FORWARD);

        telemetry.addData("Status", "Initialized");
        telemetry.update();
    }

    @Override
    public void loop() {

        //Code here will run in a continuous loop until the driver hits STOP
        //This is where we will enter the things we want the robot to do




        telemetry.addData("Left Power", leftPower);
        telemetry.addData("Right Power", rightPower);

    }
}