package org.firstinspires.ftc.teamcode;

//This is a template to start a new TeleOp OpMode
//Please do not edit this file directly.  Instead, create a new Java Class under TeamCode and copy this into it

//Import Statements Go Here
//Android Studio SHOULD Autofill These as you code
import com.qualcomm.robotcore.eventloop.opmode.TeleOp;
import com.qualcomm.robotcore.eventloop.opmode.OpMode;
import org.firstinspires.ftc.robotcore.external.Telemetry;



@TeleOp(name="AAA_TeleOp_Template", group="TeleOp") //Change "AAA_TeleOp_Template" to the name of your OpMode
public class AAA_TeleOp_Template extends OpMode {

    /*
  Change "AAA_TeleOp_Template" to the name of your OpMode
  Declare Variables Here
  For Example, "private DcMotor leftDrive" which creates a variable of the name "leftDrive" and the type "DcMotor"
  */



    @Override
    public void init() {

        //Code here will be run once when the driver hits INIT
        //This would be a good place to initialize your hardware
        //For Example, "leftDrive = hardwareMap.get(DcMotor.class, "left_drive");"


        telemetry.addData("Status", "Initialized");
        telemetry.update();
    }

    @Override
    public void loop() {

        //Code here will run in a continuous loop until the driver hits STOP
        //This is where we will enter the things we want the robot to do
        //For Example, "leftDrive.setPower(gamepad1.left_stick_y);"


    }
}